name: slack-notification

on: [push, pull_request, issues]

jobs:
    slack-notifications:
        runs-on: ubuntu-20.04
        name: Sends a message to slack when a push, a pull request or an issue is made
        steps:
            - name: Send a message to slack api
              uses: slackapi/slack-github-action@v2.0.0
            #   uses: archieve/github-actions-slack@v2.0.0
              id: notify
              with:
                slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
                slack-channel: C086E8173EK
                slack-text: Hello! Event "${{ github.event_name }}" in "${{ github.repository }}"
            - name: Result from "Send Message"
              run: echo "the result was ${{ steps.notify.outputs.slack-result }}"