name: CI Automation

on:
    pull_request: ~

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
defaults:
    run:
        shell: bash
env:
    EXIT-CODE-MISSING-DEFAULT-REQUIREMENTS: 1 #Missing package.json default env
    NODE_VERSION: 16.19.0
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build, Lint & Test
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Earlybird Scan
                uses: a-me-x-eng/earlybird-scan@v2
                with:
                    fail-severity: medium
                    fail-confidence: medium
                    display-severity: medium
                    display-confidence: high
            -   name: Setup Node
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ env.NODE_VERSION }}
        
            -   name: Node and NPM version
                run: |
                    node -v
                    npm -v
            -   name: Install Dependencies
                run: npm ci
            -   name: Build
                run: npm run build -- --concurrency 4
            # -   name: Lint
            #     run: npm run lint
            # -   name: Test
            #     run: npm run test:ci